name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          tools: composer

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Check security vulnerabilities
        run: composer audit --no-dev

      - name: Check PHPUnit binary
        run: |
          if [ ! -f vendor/bin/phpunit ]; then
            echo "::error::PHPUnit not found. Please run 'composer require --dev phpunit/phpunit'"
            exit 1
          fi

      - name: Run tests
        run: vendor/bin/phpunit tests
